namespace CodeContext.Core.Instances
{
    public class InstanceRecord
    {
        public string RootPath { get; set; } = string.Empty;
        public int Port { get; set; }
        public int Pid { get; set; }
        public string Backend { get; set; } = "inmemory";
        public DateTimeOffset StartedAt { get; set; }

        /// <summary>
        /// Random identifier generated by the host at startup. Distinguishes this instance
        /// from an unrelated process that later reuses the same PID or port, and is required
        /// by /api/shutdown so a stale record cannot stop the wrong process.
        /// </summary>
        public string InstanceId { get; set; } = string.Empty;

        /// <summary>
        /// OS-reported start time of the host process, captured at registration.
        /// Used together with the PID as a process-identity fingerprint.
        /// </summary>
        public DateTimeOffset? ProcessStartTime { get; set; }
    }

    public class InstanceRegistryDocument
    {
        public int Version { get; set; } = 1;
        public List<InstanceRecord> Instances { get; set; } = new();
    }
}
